---
functional:
  - Пользователь должен иметь возможность создавать игру или посылать ссылку на игру другому человеку
  - Пользователь должен иметь возможность выбирать соперника
  - Пользователь должен иметь возможность настравать сложность игры
  - Пользователь должен иметь возможность настаивать время игры
  - Пользователь должен иметь возможность выбирать язык программирования в игре
  - Пользователь должен иметь возможность видеть задание в игре
  - Пользователь должен иметь возможность печатать и удалять код во время игры
  - Пользователь должен иметь возможность проверить свое решение и видеть вывод тестов
  - Пользователь должен иметь возможность видеть код соперника
  - Пользователь должен иметь возможность видеть чат и писать в чат во время игры
  - Пользователь должен иметь возможность сбросить свой код
  - Пользователь должен иметь возможность сдаться
  - Пользователь должен иметь возможность наблюдать за игрой в качестве зрителя
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность видеть свой рейтинг и рейтинг других игроков
  - Пользователь должен иметь возможность переключать светлую/темную тему в редакторе кода
  - Пользователь должен иметь возможность видеть таймер времени с начала запуска игры
  - Пользователь должен иметь возможность видеть сложность заданий в лобби
  - Пользователь должен иметь возможность видеть онлайн-игроков в лобби
  - Пользователь должен иметь возможность видеть свою статистику и активность 
